--auto-generated table by generate_table.lua

local Sprite-0001_img = {
  img = "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\
ddddddddddddddddddddddddddddddttttttttttdddddddddddddddddddddddd ddddddddddddddddddddddddddddddttttttttttdddddddddddddddddddddddd ddddddddddddddddddddddddddddddttttttttttdddddddddddddddddddddddd\
ddddddddddddddddddddttttttttttttttttttttttttttttdddddddddddddddd ddddddddddddddddddddttttttttttttttttttttttttttttdddddddddddddddd ddddddddddddddddddddttttttttttttttttttttttttttttdddddddddddddddd\
ddddddddddddddddddddttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddddttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddddttttttttttttttttttttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd ddddttttttddddddddttttttttttttttttttttttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttttttttttttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd ddddttttttttddddddttttttttttttllttttllttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd ddddttttttttttddddttttttttttttllttttllttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd ddddttttttttttddddttttttttttttllttttllttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd ddddttttttttttttddttttttttttttllttttllttttttttttttdddddddddddddd ddddddddddddddddddttttttttttttllttttllttttttttttttdddddddddddddd\
ddddddddddddddddddttttttttttttttttttttttttttttttttttdddddddddddd ddddttttttttttttttttttttttttttttttttttttttttttttttttdddddddddddd ddddddddddddddddddttttttttttttttttttttttttttttttttttdddddddddddd\
ddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddddddd ddddttttttttttttttttttttttttttttttttttttttttttttttttdddddddddddd ddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddddddd\
ddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddddddd ddddddttttttttttttttttttttttttttttttttttttttttttttttdddddddddddd ddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddddddd\
ddddddddddddddttttttttttttttttttttttttttttttttttttttttdddddddddd ddddddttttttttttttttttttttttttttttttttttttttttttttttttdddddddddd ddddddddddddddttttttttttttttttttttttttttttttttttttttttdddddddddd\
ddddddddddddddttttttttttttttttttttttttttttttttttttttttdddddddddd ddddddddttttttttttttttttttttttttttttttttttttttttttttttdddddddddd ddddddddddddttttttttttttttttttttttttttttttttttttttttttdddddddddd\
ddddddddddddddttttttttttttttttttttttttttttttttttttttttdddddddddd ddddddddddttttttttttttttttttttttttttttttttttttttttttttdddddddddd ddddddddddttttttttttttttttttttttttttttttttttttttttttttdddddddddd\
ddddddddddddddttttttttttttttttttttttttttttttttttttttttttdddddddd ddddddddddddttttttttttttttttttttttttttttttttttttttttttttdddddddd ddddddddttttttttttttttttttttttttttttttttttttttttttttttttdddddddd\
ddddddddddddttttttttttttttttttttttttttttttttttttttttttttdddddddd ddddddddddddttttttttttttttttttttttttttttttttttttttttttttdddddddd ddddddddttttttttttttttttttttttttttttttttttttttttttttttttdddddddd\
ddddddddddddttttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddddddddttttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdddd\
ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddttttttttttttttttttttttttttttttttttttttttttttttttttttttdddd\
ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddttttttttttttttttttttttttttttttttttttttttttttttttttttttdddd\
ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttttdd ddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttttdd ddddddttttttttttttttttttttttttttttttttttttttttttttttttttttttttdd\
ddddddddtttttttttttttttttttttttttttttttttttttttttttttttttttttttt ddddddddtttttttttttttttttttttttttttttttttttttttttttttttttttttttt ddddddtttttttttttttttttttttttttttttttttttttttttttttttttttttttttt\
ddddddddtttttttttttttttttttttttttttttttttttttttttttttttttttttttt ddddddddtttttttttttttttttttttttttttttttttttttttttttttttttttttttt ddddddddtttttttttttttttttttttttttttttttttttttttttttttttttttttttt\
ddddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdd ddddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdd ddddddddddttttttttttttttttttttttttttttttttttttttttttttttttttttdd\
ddddddddddddddttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddddddddddttttttttttttttttttttttttttttttttttttttttttttttdddd ddddddddddddddttttttttttttttttttttttttttttttttttttttttttttttdddd\
ddddddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddd ddddddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddd ddddddddddddddddddddttttttttttttttttttttttttttttttttttttdddddddd\
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
}

return Sprite-0001_img